DROP TABLE IF EXISTS colours CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS combinations CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE colours (
  id SERIAL PRIMARY KEY NOT NULL,
  value VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE combinations (
  id SERIAL PRIMARY KEY NOT NULL,
  likes INTEGER,
  colour_1 INTEGER REFERENCES colours(id) ON DELETE CASCADE,
  colour_2 INTEGER REFERENCES colours(id) ON DELETE CASCADE,
  colour_3 INTEGER REFERENCES colours(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);